name: Reusable workflow

on:
  workflow_call:
    inputs:
      stage:
        description: Stage
        required: true
        type: string
jobs:
  build:
    environment: 
      name: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
