name: Reusable workflow

on:
  workflow_call:
    inputs:
      stage:
        description: Stage
        required: true
        type: string
    # secrets:
    #   MY_SECRET:
    #     description: Caller secret
    #     required: true
jobs:
  build:
    environment: 
      name: reuse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! I am in - ${{ inputs.stage }}
        
      - name: What is my secret
        run: echo My secret is - ${{secrets.MY_SECRET}} | sed 's/./& /g'
